M48
; DRILL file {KiCad 8.0.3} date 2024-08-18T22:06:27+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-18T22:06:27+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T1
X98.3Y-98.465
X98.3Y-103.465
T2
X121.5Y-96.0
X121.5Y-106.0
X121.5Y-124.0
X121.5Y-137.0
T3
X118.5Y-130.7
M30
